services:
  sorteggio-anime:
    build: .
    # ports:
    # - "8080:80"
    restart: always
    container_name: sorteggio-anime
    networks:
      - plv_network

networks:
  plv_network:
    external: true
